# Generated by Django 5.0.7 on 2024-09-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='pagamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='situacao',
            field=models.CharField(choices=[('AB', 'Aberto'), ('FE', 'Fechado')], default='AB', max_length=2),
        ),
    ]
