# Generated by Django 5.0.7 on 2024-09-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0002_comanda_pagamento_alter_comanda_situacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='pagamento',
            new_name='custo',
        ),
    ]
